apiVersion: v1
kind: PersistentVolume
metadata:
  name: mylogvol
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  awsElasticBlockStore:
    volumeID: vol-0c791e617ab04c96a
    fsType: ext4
